sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arjunmanevannan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arjunmanevannan/docker-react npm run test
